### ISSUE TITLE
Can it be used for multiple css layers in one global container?

### ISSUE THREAD

**Issue by sshyran** [aMoniker/jquery.videocover#2]
Hi, 
This code looks awesome. The problem is that I need to put a video (webm, mp4, ogg and/or embedded from YouTube... with fallback to an image on mobiles) under three layers: 
1) grey semi-transparent fullscreen overlay over the video (to make video unclicable);
2) a semi-transparent (80% width and height) responsive layer with css markup, images and so on;
3) and a front end layer with css styled php code.

So, question is: can this code be appended to all three layers, in order to gradualy scale up and down on all devices while being put into a dropdown clickable menu container? [final aim is fullscreen responsive website menu with a video on the background]

p.s. - I`m new to all this, I`ve already grabbed some code at w3schools, stackowerflow, and from opensource html5 videoplayer projects... but.. I just can`t make ends meet and put it all one under another. Played with z-index, viewport and @media maxwidth... but only succeeded to put it all into dropdown container.

Sorry for such a messy issue, can you help with that?

**Comment by aMoniker** [comment]
There are definitely ways to make all of that happen. It's not a simple question though, and isn't related to an issue with this library, so perhaps you'd be better served by looking for a developer for hire.

**Comment by sshyran** [comment]
Thanks for a fast reply, I just wanted to know if this code sutable for resizing different objects at once (scale in and out properly)?

**Comment by aMoniker** [comment]
Yes, you can use it on multiple elements.

**Comment by sshyran** [comment]
Can you provide an example of  jquery.videocover code structure  for doing it with 2 or 3 objects at once please?

**Comment by aMoniker** [comment]
You would just call the function once for however many elements you'd like. If you're looking for any other specific functionality though, I'm happy to accept pull requests.

**Comment by sshyran** [comment]
Ok, what are he right calls to it... 'if function exist'.... 'require once'.... or maybe  'echo'? Which part of the code is primary... to which i can call to? can you give an  example of call to primary function in jquery.videocover code?

p.s. - should I create new var`s for each new object?

**Comment by aMoniker** [comment]
This is not the place for an introductory programming lesson. You really should hire a developer or be prepared to spend a significant amount of time learning by doing.
